##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.14.1] date: [Mon Aug 09 17:24:47 CEST 2021]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = wmc


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
core/Src/main.c \
core/Src/audiolog.c \
core/Src/wmc.c \
core/Src/wmc_data.c \
core/Src/wmc_processing.c \
core/Src/wmc_tables.c \
core/Src/ai.c \
core/Src/sd_diskio_SensorTile.box.c \
core/Src/stm32l4xx_it.c \
core/Src/system_stm32l4xx.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dfsdm_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_sd_ex.c \
drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_ll_sdmmc.c \
middlewares/Third_Party/FreeRTOS/Source/croutine.c \
middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
middlewares/Third_Party/FreeRTOS/Source/list.c \
middlewares/Third_Party/FreeRTOS/Source/queue.c \
middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
middlewares/Third_Party/FreeRTOS/Source/tasks.c \
middlewares/Third_Party/FreeRTOS/Source/timers.c \
middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
middlewares/Third_Party/FatFs/src/ff.c \
middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
middlewares/Third_Party/FatFs/src/diskio.c \
drivers/BSP/SensorTile.box/SensorTile.box.c \
drivers/BSP/SensorTile.box/SensorTile.box_audio.c \
drivers/BSP/SensorTile.box/SensorTile.box_sd.c \
syscalls.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32l4r9xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L4R9xx


# AS includes
AS_INCLUDES =  \
-Icore\Inc

# C includes
C_INCLUDES =  \
-Icore/Inc \
-Idrivers/STM32L4xx_HAL_Driver/Inc \
-Idrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-Imiddlewares/Third_Party/FreeRTOS/Source/include \
-Imiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-Imiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-Imiddlewares/Third_Party/FatFs/src/ \
-Imiddlewares/Third_Party/FatFs/src/drivers \
-Imiddlewares/ST/AI/Inc \
-Idrivers/CMSIS/Device/ST/STM32L4xx/Include \
-Idrivers/CMSIS/Include \
-Idrivers/CMSIS/DSP/Include \
-Idrivers/BSP/Components/Common \
-Idrivers/BSP/SensorTile.box

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g3 -gdwarf-2
endif

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L4R9ZIJx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR = middlewares/ST/AI/Lib/NetworkRuntime700_CM4_GCC.a drivers/CMSIS/DSP/Lib/GCC/libarm_cortexM4lf_math.a
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
